---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "mimic.fullname" . }}-backend
  labels:
{{ include "mimic.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mimic.name" . }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mimic.name" . }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: {{ .Values.backend.image.registry }}:{{ .Values.backend.image.tag }}
          env:
            - name: UPSTREAM_URL
              value: {{ .Values.backend.upstream }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "mimic.fullname" . }}-frontend
  labels:
{{ include "mimic.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mimic.name" . }}
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mimic.name" . }}
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: {{ .Values.frontend.image.registry }}:{{ .Values.frontend.image.tag }}
          env:
            - name: UPSTREAMHOST
              value: ws{{ if $.Values.ingress.tls }}s{{ end }}://{{ .Values.fqdn }}/websocket
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: app
              readOnly: true
              mountPath: /app/signalling.yml
              subPath: signalling.yml
      volumes:
        - name: app
          configMap:
            name: signalling-configuration
            defaultMode: 420