---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimic.fullname" . }}-backend
  labels:
{{ include "mimic.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mimic.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      protocol: {{ .Values.backend.service.protocol | default "TCP" }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimic.fullname" . }}-frontend
  labels:
{{ include "mimic.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mimic.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      protocol: {{ .Values.frontend.service.protocol | default "TCP" }}
      targetPort: http